apiVersion: 1
datasources:
  - name: cloudwatch
    type: cloudwatch
    uid: cloudwatch
    access: proxy
    jsonData:
      authType: ec2_iam_role
      defaultRegion: us-east-2
    editable: false
