apiVersion: 1
datasources:
  - name: AWS-CloudWatch
    type: cloudwatch
    uid: aws-cloudwatch-infra
    access: proxy
    jsonData:
      authType: ec2_iam_role
      defaultRegion: us-east-2
    editable: true
